# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.12-slim
WORKDIR /app

# Install dependencies
RUN pip install --no-cache-dir httpx mcp

# Copy application code
COPY . /app

# Ensure weather.py is executable
RUN chmod +x weather.py

# Default command
CMD ["python", "weather.py"]
